os:
  - linux
  - osx
language: c
sudo: required
env:
  - EMULATOR=simh
  - EMULATOR=klh10
install: sh -ex build/dependencies.sh install_${TRAVIS_OS_NAME:-linux}
script: make
notifications:
  email: lars@nocrew.org
